"""
Convert the enrollment import CSV into a SQL file ready for phpMyAdmin upload.

Why this exists:
  Tigertech disables remote MySQL by default (and rotates dynamic IPs even
  when enabled). When update_enrollment.py can't connect directly, the fallback
  is phpMyAdmin at
      https://your-phpmyadmin-url
  → Import → upload the .sql this script produces → Go.

Usage:
  python3 csv_to_sql.py cdenroll2526_import.csv   # year inferred from CSV
  python3 csv_to_sql.py cdenroll2526_import.csv --year 2026

Output: same basename, .sql extension (cdenroll2526_import.sql)
"""

import argparse
import csv
import os
import sys

INSERT_COLS = [
    "Dataset", "District", "School", "Year", "Indicator",
    "DemographicCategory", "Demographic", "ItemDescription",
    "Result", "Group_Total", "Active",
]
NUMERIC_COLS = {"Year", "Result", "Group_Total", "Active"}
BATCH_SIZE = 500  # rows per multi-row INSERT statement


def sql_escape(value, is_numeric):
    """Render a single CSV value as a SQL literal."""
    if value is None:
        return "NULL"
    s = str(value).strip()
    if is_numeric:
        if s == "" or s == "*":
            return "NULL"
        try:
            return str(int(float(s)))
        except ValueError:
            return "NULL"
    if s == "":
        return "NULL"
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("csv_path", help="Path to the CSV produced by process_cde_enrollment.py")
    p.add_argument("--year", help="Override the Year label (defaults to the Year column in the CSV)")
    p.add_argument("--output", help="Output SQL path (defaults to <csv_basename>.sql)")
    args = p.parse_args()

    if not os.path.exists(args.csv_path):
        print(f"Error: CSV not found: {args.csv_path}")
        sys.exit(1)

    output = args.output or os.path.splitext(args.csv_path)[0] + ".sql"

    # Pass 1: read rows, capture distinct year(s)
    with open(args.csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print("Error: CSV has no rows.")
        sys.exit(1)

    years_in_csv = sorted({r["Year"] for r in rows if r.get("Year")})
    year_label = args.year or (years_in_csv[0] if len(years_in_csv) == 1 else None)
    if year_label is None:
        print(f"Error: multiple years in CSV ({years_in_csv}); pass --year to pick one.")
        sys.exit(1)

    print(f"Rows in CSV: {len(rows):,}")
    print(f"Year label:  {year_label}")
    print(f"Writing:     {output}")

    col_list = ", ".join(INSERT_COLS)

    with open(output, "w", encoding="utf-8") as out:
        out.write("-- Generated by csv_to_sql.py from " + os.path.basename(args.csv_path) + "\n")
        out.write("-- Upload to phpMyAdmin → datadashboard → Import tab → Go\n")
        out.write("-- \n")
        out.write("-- Transaction-wrapped: if any statement fails, the whole import rolls back.\n\n")
        out.write("START TRANSACTION;\n\n")

        # Delete existing rows for this year first (matches update_enrollment.py behavior)
        out.write(
            f"DELETE FROM public_datasets "
            f"WHERE Dataset = 'Enrollment' AND Indicator = 'Enrollment' "
            f"AND Year = {int(year_label)};\n\n"
        )

        # Multi-row INSERTs, batched
        for i in range(0, len(rows), BATCH_SIZE):
            batch = rows[i : i + BATCH_SIZE]
            out.write(f"INSERT INTO public_datasets ({col_list}) VALUES\n")
            value_lines = []
            for r in batch:
                vals = []
                for col in INSERT_COLS:
                    v = r.get(col, "")
                    if col == "Group_Total" and (v is None or str(v).strip() == ""):
                        v = "0"
                    vals.append(sql_escape(v, col in NUMERIC_COLS))
                value_lines.append("  (" + ", ".join(vals) + ")")
            out.write(",\n".join(value_lines))
            out.write(";\n\n")

        out.write("COMMIT;\n")

    size_mb = os.path.getsize(output) / (1024 * 1024)
    print(f"  ✓ {output}  ({size_mb:.1f} MB)")
    print()
    print("Next: https://your-phpmyadmin-url")
    print("      → Import tab → Choose File → Go")


if __name__ == "__main__":
    main()
